### ISSUE TITLE
Presence not updating

### ISSUE THREAD

**Issue by juneflowers** [soup-jingle/quodlibet-discord-richpresence#1]
Hi I just started using Quod Libet and would really like to have this functionality. I noticed there isn't any information on correctly using this but I assumed you were meant to put the .py file into quod libets plugin directory so I did that and it does show up in the list of plugins and after enabling it nothing happens. I looked at the code and saw DEFAULT_CLIENTID = "" so I set it to a new application ID i created in discords developer console but still it does not update my discord presence. Am I missing something?

**Comment by patrickbunetic** [comment]
Apologies, I really need to get around to writing the documentation for getting it set up. But you already have the application set up, and that's most of the work.

- You should set the `Client ID` in the plugins settings through _Quod Libet_ itself.

- There is a bit of a bug right now where it will not update the status if _Discord_ is opened after _Quod Libet_, so simply closing _Quod Libet_ and opening it again should resolve that.

- Lastly — and this is probably already the case — the 'Activity Status' setting needs to be turned on in _Discord_

**Comment by juneflowers** [comment]
Hey no worries thanks for responding so quickly. I tried closing and restarting them both but no luck. Also Activity Status is enabled in discord however Quod Libet shows no options whatsoever for the plugin. It's blank like this.
![image](https://user-images.githubusercontent.com/63337938/132999277-de25b76e-28ac-4e37-97cb-23d2109940de.png)

**Comment by patrickbunetic** [comment]
Can I see what the errors are under 'Show Errors' in the plugins options?
There is probably at least one missing python library

**Comment by juneflowers** [comment]
Oh i guess i'm missing everything

![image](https://user-images.githubusercontent.com/63337938/132999717-810695ce-77e1-4c3a-aa09-7c1c0db41489.png)

**Comment by patrickbunetic** [comment]
It appears so. Anything under `drpp` is what you will need to fix that.
I know I forgot to mention you will definitely need to get `pypresence`, but if there are no boxes in the options, it's possible you will need the `pygobject` module as well (though it shouldn't be the case, it may just be a general problem caused by lack of `pypresence`).

It appears you are in linux, correct? So likely, hopefully, a simple `pip install pypresence pygobject` may help. And any other python modules you may need.
(While you are at it, you can resolve any other of the plugin errors by getting those missing modules as well if they bug you enough. The only one I see in your screenshot is `paho-mqtt`)

**Comment by juneflowers** [comment]
I installed pyobject pypresence and paho-mqtt. I used sudo pip3 though. is that a problem? Nothing changed in the settings. I'm on ubuntu 21.04 btw
![image](https://user-images.githubusercontent.com/63337938/133001429-77b3b0cf-a35a-4429-8bde-173095983fc4.png)

**Comment by patrickbunetic** [comment]
Do you have text boxes in, for example, the `MQTT Publisher` or `Gajim Status Message` plugin settings? If not, that helps narrow it down to being something specific to this plugin

**Comment by juneflowers** [comment]
Yeah i have boxes there. I set up scrobbling earlier. it's only this plugin without boxes
![image](https://user-images.githubusercontent.com/63337938/133001847-a23b6322-572d-4e34-97fc-c4e3e2bf8a42.png)

**Comment by patrickbunetic** [comment]
I will try to figure out what the cause of that is sometime this week
In the meantime, it **may** be a workaround that you edit the _Quod Libet_ config manually.
Add these lines anywhere under the `[plugins]` section (of, probably, `~/.config/quodlibet/config`):

> quodlibet.fake.plugins.drpp.error = enabled
quodlibet.fake.plugins.drpp_bcurrent = 
quodlibet.fake.plugins.drpp_bpattern = \<artist\>, \<album\>
quodlibet.fake.plugins.drpp_cid = `YOUR_CLIENT_ID`
quodlibet.fake.plugins.drpp_enabled = 1
quodlibet.fake.plugins.drpp_tcurrent = 
quodlibet.fake.plugins.drpp_tpattern = \<title\>

Or make your patterns whatever you want them to be. Then restart _Quod Libet_.

I think it doesn't matter whether you put a 0 or 1 at `drpp_enabled`; there is a problem here I need to find that keeps setting it to 0 though it continues to work for me. It should be a 1, though. It's still rough, there are bugs I have to work out and I haven't looked at this in a while once I got it working well enough for me.

**Comment by juneflowers** [comment]
Thanks I appreciate it, I will report back whether I have any success. Appreciate you trying to help~

**Comment by juneflowers** [comment]
No luck. Didn't make any difference.
![image](https://user-images.githubusercontent.com/63337938/133004092-3b42e714-ea04-45c7-9450-63bd3b611837.png)

**Comment by patrickbunetic** [comment]
Are there any new errors showing up in the plugins errors now that "error" is enabled?

**Comment by juneflowers** [comment]
No but I just tried starting quod libet from the terminal and it does display errors
![image](https://user-images.githubusercontent.com/63337938/133005856-3b92da5e-471d-49f4-978e-330fc1f2e741.png)

**Comment by patrickbunetic** [comment]
Now that is interesting, I changed the file name. So the lines I told you to add to the config earlier, change all the `drpp` to `discordrp`.
Also, further up in the `[plugins]` section still, there is an `active_plugins` variable. Make sure `DiscordNowPlaying` is listed there.

Also if there is a dbus error, it may be necessary to ensure you are completely killing _Quod Libet_ before restarting.

**Comment by juneflowers** [comment]
You're a hero. It works now!
![image](https://user-images.githubusercontent.com/63337938/133006652-c9ffb354-b7ea-4d7f-9ba4-ac93770ca8f0.png)

**Comment by juneflowers** [comment]
Unrelated suggestion if you ever find the time and/or desire. It does appear to be possible nowadays to upload album covers to be displayed. I use this plugin for Musicbee when i'm on windows occasionally.
https://github.com/maybeclean/musicbee-rich-presence
It's a C# project but perhaps you could draw something from it.
Either way thanks a lot for your time~
